name: Quality

on:
  push:
    branches: [main]
  pull_request:

jobs:
  mise-doctor:
    name: Mise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
      - run: mise doctor
